version: "1.0"
info:
  model: int-scaffold
packages:
- name: Demo_TISProject
  gitServerName: siddharth_git
  gitUrl: https://github.com/siddharthsethi11
  gitUsername: siddharthsethi11
  gitBranch: main
